// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/dynamicCom/A.vue')['default']
    AsyncCom: typeof import('./src/components/AsyncCom.vue')['default']
    B: typeof import('./src/components/dynamicCom/B.vue')['default']
    C: typeof import('./src/components/dynamicCom/C.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teleport: typeof import('./src/components/Teleport.vue')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
    WaterFall: typeof import('./src/components/WaterFall.vue')['default']
  }
}
