// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/dynamicCom/A.vue')['default']
    AsyncCom: typeof import('./src/components/AsyncCom.vue')['default']
    B: typeof import('./src/components/dynamicCom/B.vue')['default']
    BusA: typeof import('./src/components/Bus/BusA.vue')['default']
    BusB: typeof import('./src/components/Bus/BusB.vue')['default']
    C: typeof import('./src/components/dynamicCom/C.vue')['default']
    CssStyle: typeof import('./src/components/CssStyle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    Inject: typeof import('./src/components/Inject.vue')['default']
    MittA: typeof import('./src/components/Mitt/MittA.vue')['default']
    MittB: typeof import('./src/components/Mitt/MittB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teleport: typeof import('./src/components/Teleport.vue')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
    WaterFall: typeof import('./src/components/WaterFall.vue')['default']
  }
}
